import{a as S,i as g,S as M}from"./assets/vendor-b11e2a50.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))p(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&p(a)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function p(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const q="https://pixabay.com/api/";async function y(e,o){return(await S(q,{params:{key:"43997530-fac9ffe50b9517751943b9e7a",q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:15}})).data}function v(e){return`<li class="img-item">
    <a class="img-link" href="${e.largeImageURL}">
    <img class="image" src ="${e.webformatURL}" alt ="${e.tags}">
    </a>
    <div class="img-info">
    <p class="info"><b>Likes</b>${e.likes}</p>
    <p class="info"><b>Views</b>${e.views}</p>
    <p class="info"><b>Comments</b>${e.comments}</p>
    <p class="info"><b>Downloads</b>${e.downloads}</p>
    </div>
    </li>`}function b(e){return e.map(v).join("")}const $=document.querySelector(".form"),l=document.querySelector(".gallery"),L=document.querySelector(".loader"),u=document.querySelector(".btn-load-more");$.addEventListener("submit",T);u.addEventListener("click",x);let s=1,i="",f;function O(){f=new M("gallery, a",{captionsData:"alt",captionDelay:250})}O();m();async function T(e){if(e.preventDefault(),l.innerHTML="",m(),w(),s=1,i=e.target.elements.query.value.trim(),!i){d(),c();return}try{const o=await y(i,s);if(o.hits.length===0)c();else{const n=b(o.hits);l.innerHTML=n,f.refresh(),B()}}catch{c()}finally{e.target.reset(),d()}}async function x(){s+=1,w();const e=await y(i,s);try{const o=b(e.hits);l.insertAdjacentHTML("beforeend",o),f.refresh(),F();const n=Math.ceil(e.totalHits/e.hits.length);s>=n&&(m(),h())}catch{h()}finally{d()}}function w(){L.style.display="block"}function d(){L.style.display="none"}function B(){u.classList.remove("hidden")}function m(){u.classList.add("hidden")}function c(){g.error({message:"Sorry, there are no images matching your search query.",messageColor:"#FAFAFB",color:"#EF4040",position:"topRight"})}function h(){g.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}function F(){const o=document.querySelector(".img-item").getBoundingClientRect().height;window.scrollBy({left:0,top:o,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
